/**
 * Fetches data from a specified URL using the POST method.
 * @param {string} key - The key generated by swr hook.
 * @param {string} url - The URL to fetch data from.
 * @param {number} currentPage - The current page number.
 * @param {number} batchSize - The number of items to fetch.
 * @returns {Promise<any>} - A promise that resolves to the fetched data.
 * @throws {Error} - If there is an error while fetching the data.
 */
export async function fetcher (key, url, currentPage, batchSize) {
  const path = url + `?page=${currentPage}&size=${batchSize}`
  const response = await fetch(path, {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ ...JSON.parse(key) })
  }).then((res) => res.json())
  return response
}
