apiVersion: v1
kind: Secret
metadata:
  name: marketplace-frontend-secret
  namespace: marketplace-frontend
type: Opaque
stringData:
  .env.production: |
    BATCH_SIZE="${BATCH_SIZE}"
    CATALOGUE_URL="http://jena-fuseki.catalogue.svc.cluster.local:3030"
    RECOMMENDER_URL="http://recommender.recommender.svc.cluster.local:8000"
    BROKER_URL="http://api-gateway.stellio.svc.cluster.local:8080"
    NEXT_PUBLIC_DLT_BOOTH_URL="http://dlt-booth.dlt-booth.svc.cluster.local:8085"
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: marketplace-frontend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_REGISTRY_CREDENTIALS}
---

